Title:
  vampire:
    1: 男爵
    2: 公爵
    3: 领主
    4: 长老
    5: 亲王
  giant:
    1: 破坏者
    2: 横冲直撞
    3: 钢铁先锋
    4: 刀枪不入
    5: 绝对防御
  human:
    1: 元婴
    2: 渡劫
    3: 地仙
    4: 天仙
    5: 神人
  monster:
    1: 小妖
    2: 妖尊
    3: 妖王
    4: 妖神
    5: 大圣